services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: promotions
    environment:
      - APP_ENV=${APP_ENV:-local}
      - DATA_SOURCE=${DATA_SOURCE:-json}
    working_dir: /var/www
    volumes:
      - ../:/var/www
    networks:
      - app-network
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - ${APP_PORT:-8000}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../:/var/www
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge