services:
  app:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
      target: db-instance
    container_name: promotions
    environment:
      - APP_ENV=${APP_ENV:-local}
      - ENV_FILE=${ENV_FILE:-.env.db}
      - DB_DRIVER=${DB_DRIVER}
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
    working_dir: /var/www
    volumes:
      - ../:/var/www
    networks:
      - app-network

  database:
    image: mysql:8.0
    container_name: promotions_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT:-3306}:${DB_PORT:-3306}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./.db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
